# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ca1782a3d5d52126f3c8e9282d2dfc9fbeed111c884a745d9329b2c73e801ae9ecb97313d23969c5fa7d4b66de958691fe55c67a9b698a66a1d73571bd0465c

test:
  secret_key_base: 47d52847852c8b5a9a54b6c8defc65e3b80166e660319099890fce140f151f82f1fd68ab992ab0efe540c45afdc06b64e6a3c7d57b973bc11c19a01651ecd465

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
